package com.redhat.ceylon.ide.netbeans.problems;

import javax.swing.tree.TreeModel;

import org.openide.windows.TopComponent;

public abstract class AbstractProblemsViewTopComponent extends TopComponent {

    public AbstractProblemsViewTopComponent() {
        preInitComponents();
    	initComponents();
    }

    abstract void preInitComponents();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        problemsTree = new javax.swing.JTree();

        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBounds(new java.awt.Rectangle(0, 0, 300, 100));

        problemsTree.setModel(createModel());
        problemsTree.setBounds(new java.awt.Rectangle(0, 0, 300, 334));
        problemsTree.setRootVisible(false);
        jScrollPane1.setViewportView(problemsTree);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JTree problemsTree;
    // End of variables declaration//GEN-END:variables

    abstract TreeModel createModel();
}
