/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.redhat.ceylon.ide.netbeans.problems;

import javax.swing.tree.TreeModel;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Displays project errors in a tool window.
 */
@ConvertAsProperties(
        dtd = "-//com.redhat.ceylon.ide.netbeans.problems//ProblemsView//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "ProblemsViewTopComponent",
        iconBase = "icons/ceylon.png",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "bottomSlidingSide", openAtStartup = false)
@ActionID(category = "Window", id = "com.redhat.ceylon.ide.netbeans.problems.ProblemsViewTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_ProblemsViewAction",
        preferredID = "ProblemsViewTopComponent"
)
@Messages({
    "CTL_ProblemsViewAction=ProblemsView",
    "CTL_ProblemsViewTopComponent=ProblemsView Window",
    "HINT_ProblemsViewTopComponent=This is a ProblemsView window"
})
public abstract class AbstractProblemsViewTopComponent extends TopComponent {

    public AbstractProblemsViewTopComponent() {
        preInitComponents();
    	initComponents();
    }

    abstract void preInitComponents();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        problemsTree = new javax.swing.JTree();

        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBounds(new java.awt.Rectangle(0, 0, 300, 100));

        problemsTree.setModel(createModel());
        problemsTree.setBounds(new java.awt.Rectangle(0, 0, 300, 334));
        problemsTree.setRootVisible(false);
        jScrollPane1.setViewportView(problemsTree);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JTree problemsTree;
    // End of variables declaration//GEN-END:variables

    abstract TreeModel createModel();
}
